language: node_js

services:
  - docker

before_install:
  - docker-compose up -d --build
  - docker exec ligapay-adonis npm i
  - docker exec ligapay-adonis adonis migration:run

script:
  - docker exec ligapay-adonis adonis test