language: node_js

services:
  - docker

before_install:
  - docker-compose up -d --build

install:
  - docker exec ligapay-adonis npm i && adonis migration:run

script:
  - docker exec ligapay-adonis adonis test
  