sudo: required
language: node_js

node_js:
 - 11.13

services:
  - docker

script:
  - docker-compose up -d --build
  - docker exec ligapay-adonis adonis migration:run
  - docker exec ligapay-adonis npm test