sudo: required
language: node_js

node_js:
 - 11.13

services:
  - docker

install:
  - docker build . -t ligapay:latest
  - npm i

before_script:
  - docker-compose up -d

script:
  - docker exec ligapay-adonis npm run lint
  - docker exec ligapay-adonis npm test

deploy:
  provider: script
  script: sh docker/deploy.sh
  on:
      branch: develop