version: 2
jobs:
  build:
    docker:
    - image: circleci/node:11
    steps:
    - checkout
    - setup_remote_docker:
      docker_layer_caching: true
    - run:
        name: Docker compose build
        command: docker-compose build
    - run:
        name: Start containers
        command: docker-compose up -d
    - run:
        name: Apply migrations
        command: docker exec ligapay-adonis adonis migration:run
    - run:
        name: Run tests
        command: docker exec ligapay-adonis npm test

workflows:
  version: 2
  build:
    jobs:
    - build