version: 2
jobs:
  build:
    docker:
    - image: circleci/node:11
    steps:
    - checkout
    - run:
        name: docker compose build
        command: docker-compose build

  test:
    docker:
    - image: circleci/node:11
    steps:
    - run:
        name: start containers
        command: docker-compose up -d
    - run:
        name: apply migrations
        command: docker exec ligapay-adonis adonis migration:run
    - run:
        name: run tests
        command: docker exec ligapay-adonis npm test
workflows:
  version: 2
  build-test:
    jobs:
    - build
    - test:
        requires:
        - build