version: '3'

services:
  backend:
    build: .
    image: ligapay:latest
    env_file: .env
    command: adonis serve --dev
    network_mode: bridge

    volumes:
      - ./:/home/ligapay
    ports:
      - 3333:3333