version: '3'

services:
  adonis:
    build: .
    container_name: ligapay-adonis
    image: ligapay:latest
    env_file: .env

    depends_on:
      - postgres
    volumes:
      - ./:/src
    ports:
      - 3333:3333

  postgres:
    image: postgres:11.2-alpine
    container_name: ligapay-pg

    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432