version: '3'

services:
  adonis:
    build: .
    container_name: ligapay-adonis
    image: ligapay:latest
    env_file: .env
    command: adonis serve --dev

    depends_on:
      - postgres
    volumes:
      - ./:/home/ligapay
    ports:
      - 3333

  postgres:
    image: postgres:latest
    container_name: ligapay-pg

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432